/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as FinancingRouteImport } from './routes/financing'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as GalleryIndexRouteImport } from './routes/gallery.index'
import { Route as ServicesSpecialtyTradeRouteImport } from './routes/services.specialty-trade'
import { Route as ServicesResidentialRouteImport } from './routes/services.residential'
import { Route as ServicesRemodelingRouteImport } from './routes/services.remodeling'
import { Route as ServicesRealEstateRouteImport } from './routes/services.real-estate'
import { Route as ServicesKitchenRouteImport } from './routes/services.kitchen'
import { Route as ServicesFloridaCgcLicenseRouteImport } from './routes/services.florida-cgc-license'
import { Route as ServicesFinishingSystemsRouteImport } from './routes/services.finishing-systems'
import { Route as ServicesConstructionRouteImport } from './routes/services.construction'
import { Route as ServicesCommercialRouteImport } from './routes/services.commercial'
import { Route as ServicesCleaningRouteImport } from './routes/services.cleaning'
import { Route as ServicesCabinetsRouteImport } from './routes/services.cabinets'
import { Route as ServicesBathroomRouteImport } from './routes/services.bathroom'
import { Route as GalleryVideoRouteImport } from './routes/gallery.video'
import { Route as GalleryResidentialRouteImport } from './routes/gallery.residential'
import { Route as GalleryKitchenRouteImport } from './routes/gallery.kitchen'
import { Route as GalleryBathroomRouteImport } from './routes/gallery.bathroom'
import { Route as GalleryAllPhotosRouteImport } from './routes/gallery.all-photos'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancingRoute = FinancingRouteImport.update({
  id: '/financing',
  path: '/financing',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesRoute,
} as any)
const GalleryIndexRoute = GalleryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GalleryRoute,
} as any)
const ServicesSpecialtyTradeRoute = ServicesSpecialtyTradeRouteImport.update({
  id: '/specialty-trade',
  path: '/specialty-trade',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesResidentialRoute = ServicesResidentialRouteImport.update({
  id: '/residential',
  path: '/residential',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesRemodelingRoute = ServicesRemodelingRouteImport.update({
  id: '/remodeling',
  path: '/remodeling',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesRealEstateRoute = ServicesRealEstateRouteImport.update({
  id: '/real-estate',
  path: '/real-estate',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesKitchenRoute = ServicesKitchenRouteImport.update({
  id: '/kitchen',
  path: '/kitchen',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesFloridaCgcLicenseRoute =
  ServicesFloridaCgcLicenseRouteImport.update({
    id: '/florida-cgc-license',
    path: '/florida-cgc-license',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesFinishingSystemsRoute =
  ServicesFinishingSystemsRouteImport.update({
    id: '/finishing-systems',
    path: '/finishing-systems',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesConstructionRoute = ServicesConstructionRouteImport.update({
  id: '/construction',
  path: '/construction',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesCommercialRoute = ServicesCommercialRouteImport.update({
  id: '/commercial',
  path: '/commercial',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesCleaningRoute = ServicesCleaningRouteImport.update({
  id: '/cleaning',
  path: '/cleaning',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesCabinetsRoute = ServicesCabinetsRouteImport.update({
  id: '/cabinets',
  path: '/cabinets',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesBathroomRoute = ServicesBathroomRouteImport.update({
  id: '/bathroom',
  path: '/bathroom',
  getParentRoute: () => ServicesRoute,
} as any)
const GalleryVideoRoute = GalleryVideoRouteImport.update({
  id: '/video',
  path: '/video',
  getParentRoute: () => GalleryRoute,
} as any)
const GalleryResidentialRoute = GalleryResidentialRouteImport.update({
  id: '/residential',
  path: '/residential',
  getParentRoute: () => GalleryRoute,
} as any)
const GalleryKitchenRoute = GalleryKitchenRouteImport.update({
  id: '/kitchen',
  path: '/kitchen',
  getParentRoute: () => GalleryRoute,
} as any)
const GalleryBathroomRoute = GalleryBathroomRouteImport.update({
  id: '/bathroom',
  path: '/bathroom',
  getParentRoute: () => GalleryRoute,
} as any)
const GalleryAllPhotosRoute = GalleryAllPhotosRouteImport.update({
  id: '/all-photos',
  path: '/all-photos',
  getParentRoute: () => GalleryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/financing': typeof FinancingRoute
  '/gallery': typeof GalleryRouteWithChildren
  '/reviews': typeof ReviewsRoute
  '/services': typeof ServicesRouteWithChildren
  '/gallery/all-photos': typeof GalleryAllPhotosRoute
  '/gallery/bathroom': typeof GalleryBathroomRoute
  '/gallery/kitchen': typeof GalleryKitchenRoute
  '/gallery/residential': typeof GalleryResidentialRoute
  '/gallery/video': typeof GalleryVideoRoute
  '/services/bathroom': typeof ServicesBathroomRoute
  '/services/cabinets': typeof ServicesCabinetsRoute
  '/services/cleaning': typeof ServicesCleaningRoute
  '/services/commercial': typeof ServicesCommercialRoute
  '/services/construction': typeof ServicesConstructionRoute
  '/services/finishing-systems': typeof ServicesFinishingSystemsRoute
  '/services/florida-cgc-license': typeof ServicesFloridaCgcLicenseRoute
  '/services/kitchen': typeof ServicesKitchenRoute
  '/services/real-estate': typeof ServicesRealEstateRoute
  '/services/remodeling': typeof ServicesRemodelingRoute
  '/services/residential': typeof ServicesResidentialRoute
  '/services/specialty-trade': typeof ServicesSpecialtyTradeRoute
  '/gallery/': typeof GalleryIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/financing': typeof FinancingRoute
  '/reviews': typeof ReviewsRoute
  '/gallery/all-photos': typeof GalleryAllPhotosRoute
  '/gallery/bathroom': typeof GalleryBathroomRoute
  '/gallery/kitchen': typeof GalleryKitchenRoute
  '/gallery/residential': typeof GalleryResidentialRoute
  '/gallery/video': typeof GalleryVideoRoute
  '/services/bathroom': typeof ServicesBathroomRoute
  '/services/cabinets': typeof ServicesCabinetsRoute
  '/services/cleaning': typeof ServicesCleaningRoute
  '/services/commercial': typeof ServicesCommercialRoute
  '/services/construction': typeof ServicesConstructionRoute
  '/services/finishing-systems': typeof ServicesFinishingSystemsRoute
  '/services/florida-cgc-license': typeof ServicesFloridaCgcLicenseRoute
  '/services/kitchen': typeof ServicesKitchenRoute
  '/services/real-estate': typeof ServicesRealEstateRoute
  '/services/remodeling': typeof ServicesRemodelingRoute
  '/services/residential': typeof ServicesResidentialRoute
  '/services/specialty-trade': typeof ServicesSpecialtyTradeRoute
  '/gallery': typeof GalleryIndexRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/financing': typeof FinancingRoute
  '/gallery': typeof GalleryRouteWithChildren
  '/reviews': typeof ReviewsRoute
  '/services': typeof ServicesRouteWithChildren
  '/gallery/all-photos': typeof GalleryAllPhotosRoute
  '/gallery/bathroom': typeof GalleryBathroomRoute
  '/gallery/kitchen': typeof GalleryKitchenRoute
  '/gallery/residential': typeof GalleryResidentialRoute
  '/gallery/video': typeof GalleryVideoRoute
  '/services/bathroom': typeof ServicesBathroomRoute
  '/services/cabinets': typeof ServicesCabinetsRoute
  '/services/cleaning': typeof ServicesCleaningRoute
  '/services/commercial': typeof ServicesCommercialRoute
  '/services/construction': typeof ServicesConstructionRoute
  '/services/finishing-systems': typeof ServicesFinishingSystemsRoute
  '/services/florida-cgc-license': typeof ServicesFloridaCgcLicenseRoute
  '/services/kitchen': typeof ServicesKitchenRoute
  '/services/real-estate': typeof ServicesRealEstateRoute
  '/services/remodeling': typeof ServicesRemodelingRoute
  '/services/residential': typeof ServicesResidentialRoute
  '/services/specialty-trade': typeof ServicesSpecialtyTradeRoute
  '/gallery/': typeof GalleryIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/financing'
    | '/gallery'
    | '/reviews'
    | '/services'
    | '/gallery/all-photos'
    | '/gallery/bathroom'
    | '/gallery/kitchen'
    | '/gallery/residential'
    | '/gallery/video'
    | '/services/bathroom'
    | '/services/cabinets'
    | '/services/cleaning'
    | '/services/commercial'
    | '/services/construction'
    | '/services/finishing-systems'
    | '/services/florida-cgc-license'
    | '/services/kitchen'
    | '/services/real-estate'
    | '/services/remodeling'
    | '/services/residential'
    | '/services/specialty-trade'
    | '/gallery/'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/financing'
    | '/reviews'
    | '/gallery/all-photos'
    | '/gallery/bathroom'
    | '/gallery/kitchen'
    | '/gallery/residential'
    | '/gallery/video'
    | '/services/bathroom'
    | '/services/cabinets'
    | '/services/cleaning'
    | '/services/commercial'
    | '/services/construction'
    | '/services/finishing-systems'
    | '/services/florida-cgc-license'
    | '/services/kitchen'
    | '/services/real-estate'
    | '/services/remodeling'
    | '/services/residential'
    | '/services/specialty-trade'
    | '/gallery'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/financing'
    | '/gallery'
    | '/reviews'
    | '/services'
    | '/gallery/all-photos'
    | '/gallery/bathroom'
    | '/gallery/kitchen'
    | '/gallery/residential'
    | '/gallery/video'
    | '/services/bathroom'
    | '/services/cabinets'
    | '/services/cleaning'
    | '/services/commercial'
    | '/services/construction'
    | '/services/finishing-systems'
    | '/services/florida-cgc-license'
    | '/services/kitchen'
    | '/services/real-estate'
    | '/services/remodeling'
    | '/services/residential'
    | '/services/specialty-trade'
    | '/gallery/'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRoute
  ContactRoute: typeof ContactRoute
  FinancingRoute: typeof FinancingRoute
  GalleryRoute: typeof GalleryRouteWithChildren
  ReviewsRoute: typeof ReviewsRoute
  ServicesRoute: typeof ServicesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financing': {
      id: '/financing'
      path: '/financing'
      fullPath: '/financing'
      preLoaderRoute: typeof FinancingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/gallery/': {
      id: '/gallery/'
      path: '/'
      fullPath: '/gallery/'
      preLoaderRoute: typeof GalleryIndexRouteImport
      parentRoute: typeof GalleryRoute
    }
    '/services/specialty-trade': {
      id: '/services/specialty-trade'
      path: '/specialty-trade'
      fullPath: '/services/specialty-trade'
      preLoaderRoute: typeof ServicesSpecialtyTradeRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/residential': {
      id: '/services/residential'
      path: '/residential'
      fullPath: '/services/residential'
      preLoaderRoute: typeof ServicesResidentialRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/remodeling': {
      id: '/services/remodeling'
      path: '/remodeling'
      fullPath: '/services/remodeling'
      preLoaderRoute: typeof ServicesRemodelingRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/real-estate': {
      id: '/services/real-estate'
      path: '/real-estate'
      fullPath: '/services/real-estate'
      preLoaderRoute: typeof ServicesRealEstateRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/kitchen': {
      id: '/services/kitchen'
      path: '/kitchen'
      fullPath: '/services/kitchen'
      preLoaderRoute: typeof ServicesKitchenRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/florida-cgc-license': {
      id: '/services/florida-cgc-license'
      path: '/florida-cgc-license'
      fullPath: '/services/florida-cgc-license'
      preLoaderRoute: typeof ServicesFloridaCgcLicenseRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/finishing-systems': {
      id: '/services/finishing-systems'
      path: '/finishing-systems'
      fullPath: '/services/finishing-systems'
      preLoaderRoute: typeof ServicesFinishingSystemsRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/construction': {
      id: '/services/construction'
      path: '/construction'
      fullPath: '/services/construction'
      preLoaderRoute: typeof ServicesConstructionRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/commercial': {
      id: '/services/commercial'
      path: '/commercial'
      fullPath: '/services/commercial'
      preLoaderRoute: typeof ServicesCommercialRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/cleaning': {
      id: '/services/cleaning'
      path: '/cleaning'
      fullPath: '/services/cleaning'
      preLoaderRoute: typeof ServicesCleaningRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/cabinets': {
      id: '/services/cabinets'
      path: '/cabinets'
      fullPath: '/services/cabinets'
      preLoaderRoute: typeof ServicesCabinetsRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/bathroom': {
      id: '/services/bathroom'
      path: '/bathroom'
      fullPath: '/services/bathroom'
      preLoaderRoute: typeof ServicesBathroomRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/gallery/video': {
      id: '/gallery/video'
      path: '/video'
      fullPath: '/gallery/video'
      preLoaderRoute: typeof GalleryVideoRouteImport
      parentRoute: typeof GalleryRoute
    }
    '/gallery/residential': {
      id: '/gallery/residential'
      path: '/residential'
      fullPath: '/gallery/residential'
      preLoaderRoute: typeof GalleryResidentialRouteImport
      parentRoute: typeof GalleryRoute
    }
    '/gallery/kitchen': {
      id: '/gallery/kitchen'
      path: '/kitchen'
      fullPath: '/gallery/kitchen'
      preLoaderRoute: typeof GalleryKitchenRouteImport
      parentRoute: typeof GalleryRoute
    }
    '/gallery/bathroom': {
      id: '/gallery/bathroom'
      path: '/bathroom'
      fullPath: '/gallery/bathroom'
      preLoaderRoute: typeof GalleryBathroomRouteImport
      parentRoute: typeof GalleryRoute
    }
    '/gallery/all-photos': {
      id: '/gallery/all-photos'
      path: '/all-photos'
      fullPath: '/gallery/all-photos'
      preLoaderRoute: typeof GalleryAllPhotosRouteImport
      parentRoute: typeof GalleryRoute
    }
  }
}

interface GalleryRouteChildren {
  GalleryAllPhotosRoute: typeof GalleryAllPhotosRoute
  GalleryBathroomRoute: typeof GalleryBathroomRoute
  GalleryKitchenRoute: typeof GalleryKitchenRoute
  GalleryResidentialRoute: typeof GalleryResidentialRoute
  GalleryVideoRoute: typeof GalleryVideoRoute
  GalleryIndexRoute: typeof GalleryIndexRoute
}

const GalleryRouteChildren: GalleryRouteChildren = {
  GalleryAllPhotosRoute: GalleryAllPhotosRoute,
  GalleryBathroomRoute: GalleryBathroomRoute,
  GalleryKitchenRoute: GalleryKitchenRoute,
  GalleryResidentialRoute: GalleryResidentialRoute,
  GalleryVideoRoute: GalleryVideoRoute,
  GalleryIndexRoute: GalleryIndexRoute,
}

const GalleryRouteWithChildren =
  GalleryRoute._addFileChildren(GalleryRouteChildren)

interface ServicesRouteChildren {
  ServicesBathroomRoute: typeof ServicesBathroomRoute
  ServicesCabinetsRoute: typeof ServicesCabinetsRoute
  ServicesCleaningRoute: typeof ServicesCleaningRoute
  ServicesCommercialRoute: typeof ServicesCommercialRoute
  ServicesConstructionRoute: typeof ServicesConstructionRoute
  ServicesFinishingSystemsRoute: typeof ServicesFinishingSystemsRoute
  ServicesFloridaCgcLicenseRoute: typeof ServicesFloridaCgcLicenseRoute
  ServicesKitchenRoute: typeof ServicesKitchenRoute
  ServicesRealEstateRoute: typeof ServicesRealEstateRoute
  ServicesRemodelingRoute: typeof ServicesRemodelingRoute
  ServicesResidentialRoute: typeof ServicesResidentialRoute
  ServicesSpecialtyTradeRoute: typeof ServicesSpecialtyTradeRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesBathroomRoute: ServicesBathroomRoute,
  ServicesCabinetsRoute: ServicesCabinetsRoute,
  ServicesCleaningRoute: ServicesCleaningRoute,
  ServicesCommercialRoute: ServicesCommercialRoute,
  ServicesConstructionRoute: ServicesConstructionRoute,
  ServicesFinishingSystemsRoute: ServicesFinishingSystemsRoute,
  ServicesFloridaCgcLicenseRoute: ServicesFloridaCgcLicenseRoute,
  ServicesKitchenRoute: ServicesKitchenRoute,
  ServicesRealEstateRoute: ServicesRealEstateRoute,
  ServicesRemodelingRoute: ServicesRemodelingRoute,
  ServicesResidentialRoute: ServicesResidentialRoute,
  ServicesSpecialtyTradeRoute: ServicesSpecialtyTradeRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRoute,
  ContactRoute: ContactRoute,
  FinancingRoute: FinancingRoute,
  GalleryRoute: GalleryRouteWithChildren,
  ReviewsRoute: ReviewsRoute,
  ServicesRoute: ServicesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
